### ISSUE TITLE
Fractional numbers greater than 10 running outside of Zoom Display Control

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial.js#11]
This issue stems from #2 

![capture](https://cloud.githubusercontent.com/assets/4172213/22530038/c519ca24-e88e-11e6-885a-940110e88db9.PNG)

**Comment by ryanjhodge** [comment]
I can see two solutions to this:

1. Making the control responsive to fractional numbers above 10
2. Dropping the fraction and displaying the integer only for all fractional zoom levels

**Comment by nateirwin** [comment]
The second option is probably easier. I don't see any big problem with dropping the fraction.
