### ISSUE TITLE
Default to using fractional zoom levels

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial.js#2]
How do you feel about defaulting to using fractional zoom levels?

Here's a jsfiddle to get a sense of the feel of it:
https://jsfiddle.net/ryanjhodge/ay01dnxp/

_e.g._
```javascript
wheelPxPerZoomLevel: 120
zoomDelta: 0.5
zoomSnap: 0.5
```

**Comment by nateirwin** [comment]
I'm all for it! It brings more consistency with GL-based maps.

**Comment by ryanbranciforte** [comment]
+1 

@nateirwin @jmoe  This would be nice in OuterSpatial as well.
