### ISSUE TITLE
Work on z-index for baseLayers and overlays

### ISSUE THREAD

**Issue by nateirwin** [trailheadlabs/outerspatial.js#28]
Now that we're on Leaflet > 1.0, we should implement better support for z-index between all of a map's overlays.

**Comment by ryanjhodge** [comment]
I bet we can take advantage of the [`pane` option that Leaflet 1.0 introduced](http://leafletjs.com/reference-1.0.3.html#map-pane) for this one.

**Comment by ryanjhodge** [comment]
My initial thoughts are we could add an `order` and/or `pane` option to the outerspatial.js layer configuration objects and then use that information to set the layer's z index accordingly when it's added to the map. 

In leaflet >= 1.0 the layers get added to default map panes depending on they layer's leaflet class type. The default order (in increasing z index) is as follows: tile layers, vector layers, markers, tooltips, popups.  The `order` option of the layer configuration could control the z index of the layer _within_ the pane.  If the `pane` option is set, then it gets added to the specified pane, and if not, then it gets added to the default pane.

We could calculate the z index by taking the base z index of the layer's pane and adding it to the specified order of the layer.  For example the base z index of the vector pane is 400, so if we had 2 layers in the vector pane we would set them to 400 + `order` of the layer.

We can also add our own panes, for example, I could see a "labels" pane between the markers and tooltip panes being useful for maps that have a separate labels layer (i.e. the "map sandwich").  If the labels layer was tiled, by default it would be added below the vector and marker panes so markers and lines would be drawn over the label text.

I can look into seeing if the z index of layers has an affect on the order of popups, particularly when two layers with popups intersect (e.g. the issue @ryanbranciforte observed with getting two popups on top of one another in the union of two features). If not then ordering the popups might be a separate issue/solution.

**Comment by ryanbranciforte** [comment]
Thanks @ryanjhodge. Seems like a good approach, but @nateirwin will be best to make the call on the direction for this.

**Comment by nateirwin** [comment]
This could also be a UI problem. We could just force raster overlays to the "bottom" of the overlay stack and not allow them to be moved on top of vector overlays in the left-hand sidebar. So they could be reordered, but only amongst other raster overlays. And vector overlays would always show on top of raster overlays (which is what's built into Leaflet by default), but could be reordered amongst themselves.

The other option is to create individual panes for each overlay and manage the z-index programatically based on the order they're added to the map via NPMap.js. This is the most flexible option, but it'll obviously be more work to implement.

**Comment by ryanbranciforte** [comment]
Looking good!
