### ISSUE TITLE
Maki icons not showing in geojson clustered example

### ISSUE THREAD

**Issue by ryanjhodge** [trailheadlabs/outerspatial.js#33]
The layer objects in this example contains a `maki` element.  Did this once give the clustered icons a maki icon perhaps?

```
maki: {
  color: '#609321',
  name: 'park'
}
```

Was wondering if this functionality was broken at some point and we didn't realize it or if it's supposed to be: 

```
 styles: {
      point: {
        'marker-color': '#609321',
        'marker-symbol': 'park'
      }
    }
```
_e.g._
https://github.com/trailheadlabs/outerspatial.js/blob/master/examples/geojson-layer-clustered.js#L11-L13
https://github.com/trailheadlabs/outerspatial.js/blob/master/examples/geojson-layer-clustered.js#L25-L28

**Comment by nateirwin** [comment]
Hmm, seems to me like that's just outdated. If memory serves me, that's how marker symbology was setup in an earlier version of NPMap.js. Think we can just update the example...

**Comment by nateirwin** [comment]
This was fixed by @ryanjhodge
